const produtos = [

    {
        quantidade: 20,
        descricao: 'SMARTPHONE XIAOMI REDMI NOTE 8 SPACE BLACK 64GB',
        valor: 750.00,
        imagem: '/produtos/smartphone.png',
    },
    {
        quantidade: 6,
        descricao: 'FONE DE OUVIDO XIAOMI MI EARBUDS BASIC 2',
        valor: 24.03,
        imagem: '/produtos/fone-earbuds.png',
    },
    {
        quantidade: 4,
        descricao: 'CHROMECAST AMAZON FIRE STICK',
        valor: 211.49,
        imagem: '/produtos/fire-stick.png',
    },
    {
        quantidade: 1,
        descricao: 'SMARTWATCH (RELOG.INTLG.) SMART WEAR',
        valor: 120.00,
        imagem: '/produtos/smartwatch.png',
    },
    {
        quantidade: 1,
        descricao: 'REPETIDOR WIFI TP-LINK AC750',
        valor: 99.98,
        imagem: '/produtos/repetidor.png',
    },
    {
        quantidade: 2,
        descricao: 'ADAPTADOR USB TP-LINK TL-WN823N',
        valor: 31.24,
        imagem: '/produtos/adaptador.png',
    },
    {
        quantidade: 1,
        descricao: 'ROTEADOR WIFI TP-LINK TL-MR3020',
        valor: 72.10,
        imagem: '/produtos/roteador.png',
    },
    {
        quantidade: 1,
        descricao: 'CAMERA DE SEGURANCA XIAOMI MI 360 HOME',
        valor: 182.65,
        imagem: '/produtos/camera.png',
    },
    {
        quantidade: 1,
        descricao: 'CAIXA ACUSTICA JBL FLIPS',
        valor: 456.64,
        imagem: '/produtos/caixa-jbl-flips.png',
    },
    {
        quantidade: 1,
        descricao: 'CAIXA ACUSTICA ECHO DOT',
        valor: 336.47,
        imagem: '/produtos/echodot.png',
    },
    {
        quantidade: 2,
        descricao: 'CARREGADOR DE BATERIA ITEL 20000MAH',
        valor: 72.47,
        imagem: '/produtos/powerbank200.png',
    },
    {
        quantidade: 1,
        descricao: 'CARREGADOR DE BATERIA ITEL IPP-51 10000MAH',
        valor: 48.07,
        imagem: '/produtos/powerbank1000.png',
    },
    {
        quantidade: 1,
        descricao: 'PERFUME DKNY',
        valor: 240.00,
        imagem: '/produtos/perfume.png',
    },
    {
        quantidade: 1,
        descricao: 'ROTEADOR WIFI XIAOMI MI ROUTER 4A',
        valor: 240.34,
        imagem: '/produtos/roteador4a.png',
    },
    {
        quantidade: 1,
        descricao: 'CONTROLE DE VIDEO GAME MICROSOFT XBOX',
        valor: 96.13,
        imagem: '/produtos/controle.png',
    },
    {
        quantidade: 2,
        descricao: 'CONJUNTO ESPORTIVO',
        valor: 120.00,
        imagem: '/produtos/conjunto-esportivo.png',
    },
    {
        quantidade: 1,
        descricao: 'MAQUINA DE SOLDA ELETRICA YAXUN',
        valor: 432.60,
        imagem: '/produtos/maquina-solda.png',
    },
    {
        quantidade: 3,
        descricao: 'TERMINAL POS (PTO DE VENDA) MOVEL C/IMPRESSORA',
        valor: 676.85,
        imagem: '/produtos/impressora.png',
    },
    {
        quantidade: 20,
        descricao: 'JAQUETA',
        valor: 676.85,
        imagem: '/produtos/jaqueta.png',
    },
    {
        quantidade: 2,
        descricao: 'CONTADOR DE DINHEIRO QUANTA',
        valor: 50.41,
        imagem: '/produtos/contador.png',
    },
    {
        quantidade: 2,
        descricao: 'SWITCH TP-LINK TL-SG1024D',
        valor: 486.14,
        imagem: '/produtos/switch-sg1024.png',
    },
    {
        quantidade: 1,
        descricao: 'SWITCH TP-LINK TL-SG108',
        valor: 158.64,
        imagem: '/produtos/switch-sg108.png',
    },
    {
        quantidade: 1,
        descricao: 'CAIXA ACUSTICA JBL GO3',
        valor: 125.37,
        imagem: '/produtos/go3jbl.png',
    },
    {
        quantidade: 6,
        descricao: 'SSD (SOLID STATE DRIVE) HIKVISION C100 120GB',
        valor: 76.25,
        imagem: '/produtos/hdssdc100.png',
    },
    {
        quantidade: 3,
        descricao: 'HD SEAGATE EXPANSION 1TB',
        valor: 217.49,
        imagem: '/produtos/hdexterno.png',
    },
    {
        quantidade: 1,
        descricao: 'SWITCH TP-LINK TL-SG1016D',
        valor: 383.80,
        imagem: '/produtos/switch-sg1016d.png',
    },
    {
        quantidade: 26,
        descricao: 'PLACA MAE GOLINE GL-HSS-MA',
        valor: 261.23,
        imagem: '/produtos/placa-mae.png',
    },
    {
        quantidade: 1,
        descricao: 'SCOOTER ELETRICO FONTAINE 6,5',
        valor: 450.87,
        imagem: '/produtos/scooter.png',
    },
    {
        quantidade: 375,
        descricao: 'SSD (SOLID STATE DRIVE) BESTMEMORY',
        valor: 135.75,
        imagem: '/produtos/hdssd.png',
    },
    {
        quantidade: 1,
        descricao: 'MALA DE VIAGEM GRANDE',
        valor: 51.79,
        imagem: '/produtos/mala.png',
    },
];

export default produtos; 