const produtos = [
    {
        quantidade: 20,
        descricao: 'CAMARA DE AR DE MOTO',
        valor: 25.25,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 6,
        descricao: 'FONE DE OUVIDO XIAOMI MI EARBUDS BASIC 2',
        valor: 24.03,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 4,
        descricao: 'CHROMECAST AMAZON FIRE STICK',
        valor: 211.49,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 2,
        descricao: 'SMARTWATCH (RELOG.INTLG.) SMART WEAR',
        valor: 120.00,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 1,
        descricao: 'REPETIDOR WIFI TP-LINK AC750',
        valor: 99.98,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 2,
        descricao: 'ADAPTADOR USB TP-LINK TL-WN823N',
        valor: 31.24,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 1,
        descricao: 'ROTEADOR WIFI TP-LINK TL-MR3020',
        valor: 72.10,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 1,
        descricao: 'CAMERA DE SEGURANCA XIAOMI MI 360 HOME',
        valor: 182.65,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 1,
        descricao: 'CAIXA ACUSTICA JBL FLIPS',
        valor: 456.64,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 1,
        descricao: 'CAIXA ACUSTICA ECHO DOT',
        valor: 336.47,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 2,
        descricao: 'CARREGADOR DE BATERIA ITEL 20000MAH',
        valor: 72.47,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 1,
        descricao: 'CARREGADOR DE BATERIA ITEL IPP-51 10000MAH',
        valor: 48.07,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 1,
        descricao: 'PERFUME DKNY',
        valor: 240.00,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 1,
        descricao: 'ROTEADOR WIFI XIAOMI MI ROUTER 4A',
        valor: 240.34,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 1,
        descricao: 'CONTROLE DE VIDEO GAME MICROSOFT XBOX',
        valor: 96.13,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 2,
        descricao: 'VESTUARIO CONJUNTO ESPORTIVO',
        valor: 120.00,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 1,
        descricao: 'MAQUINA DE SOLDA ELETRICA YAXUN',
        valor: 432.60,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 3,
        descricao: 'TERMINAL POS (PTO DE VENDA) MOVEL C/IMPRESSORA',
        valor: 676.85,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 2,
        descricao: 'IMPRESORA QTCDD15 110V',
        valor: 316.33,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 20,
        descricao: 'CONTADOR DE DINHEIRO QUANTA',
        valor: 50.41,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 2,
        descricao: 'SWITCH TP-LINK TL-SG1024D',
        valor: 486.14,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 2,
        descricao: 'SWITCH TP-LINK TL-SG108',
        valor: 158.64,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 1,
        descricao: 'CAIXA ACUSTICA JBL GO3',
        valor: 125.37,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 6,
        descricao: 'SSD (SOLID STATE DRIVE) HIKVISION C100 120GB',
        valor: 76.25,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 3,
        descricao: 'HD SEAGATE EXPANSION 1TB',
        valor: 217.49,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 1,
        descricao: 'SWITCH TP-LINK TL-SG1016D',
        valor: 383.80,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 20,
        descricao: 'PLACA MAE GOLINE GL-HSS-MA',
        valor: 261.23,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 1,
        descricao: 'SCOOTER ELETRICO FONTAINE 6,5',
        valor: 450.87,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 42,
        descricao: 'PARTES E PECAS VEICULOS',
        valor: 15.00,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 2,
        descricao: 'PARTES E PECAS VEICULOS',
        valor: 26.95,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 375,
        descricao: 'SSD (SOLID STATE DRIVE) BESTMEMORY',
        valor: 135.75,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 15,
        descricao: 'INSTRUMENTO MEDICO RADIESSE 1.5CC',
        valor: 621.53,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 56,
        descricao: 'INSTRUMENTO MEDICO LINELIFT 29G-50MM',
        valor: 517.94,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 1,
        descricao: 'MALA DE VIAGEM GRANDE',
        valor: 51.79,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
    {
        quantidade: 20,
        descricao: 'SMARTPHONE XIAOMI REDMI NOTE 8 SPACE BLACK 64GB',
        valor: 750.00,
        imagem: 'https://via.placeholder.com/100?text=Produto',
    },
];

export default produtos; 