const produtos = [

    {
        quantidade: 20,
        descricao: 'SMARTPHONE XIAOMI REDMI NOTE 8 64GB',
        valor: 350.00,
        imagem: '/produtos/smartphone.png',
    },
    {
        quantidade: 6,
        descricao: 'FONE DE OUVIDO XIAOMI EARBUDS BASIC 2',
        valor: 45.00,
        imagem: '/produtos/fone-earbuds.png',
    },
    {
        quantidade: 4,
        descricao: 'CHROMECAST AMAZON FIRE STICK',
        valor: 130.00,
        imagem: '/produtos/fire-stick.png',
    },
    {
        quantidade: 1,
        descricao: 'SMARTWATCH SMART WEAR',
        valor: 100.00,
        imagem: '/produtos/smartwatch.png',
    },
    {
        quantidade: 1,
        descricao: 'REPETIDOR WIFI TP-LINK AC750',
        valor: 75.00,
        imagem: '/produtos/repetidor.png',
    },
    {
        quantidade: 2,
        descricao: 'ADAPTADOR USB TP-LINK TL-WN823N',
        valor: 20.00,
        imagem: '/produtos/adaptador.png',
    },
    {
        quantidade: 1,
        descricao: 'ROTEADOR WIFI TP-LINK TL-MR3020',
        valor: 70.00,
        imagem: '/produtos/roteador.png',
    },
    {
        quantidade: 1,
        descricao: 'CAMERA DE SEGURANÇA XIAOMI MI 360 HOME',
        valor: 80.00,
        imagem: '/produtos/camera.png',
    },
    {
        quantidade: 1,
        descricao: 'CAIXA DE SOM JBL FLIP 5',
        valor: 250.00,
        imagem: '/produtos/caixa-jbl-flips.png',
    },
    {
        quantidade: 1,
        descricao: 'AMAZON ECHO DOT COM ALEXA',
        valor: 150.00,
        imagem: '/produtos/echodot.png',
    },
    {
        quantidade: 2,
        descricao: 'CARREGADOR DE BATERIA POWER BANK 20000MAH',
        valor: 60.00,
        imagem: '/produtos/powerbank200.png',
    },
    {
        quantidade: 1,
        descricao: 'CARREGADOR DE BATERIA POWER BANK 10000MAH',
        valor: 40.00,
        imagem: '/produtos/powerbank1000.png',
    },
    {
        quantidade: 1,
        descricao: 'PERFUME DKNY',
        valor: 110.00,
        imagem: '/produtos/perfume.png',
    },
    {
        quantidade: 1,
        descricao: 'ROTEADOR WIFI XIAOMI MI ROUTER 4A',
        valor: 80.00,
        imagem: '/produtos/roteador4a.png',
    },
    {
        quantidade: 1,
        descricao: 'CONTROLE DE VIDEO GAME MICROSOFT XBOX',
        valor: 150.00,
        imagem: '/produtos/controle.png',
    },
    {
        quantidade: 2,
        descricao: 'CONJUNTO ESPORTIVO',
        valor: 65.00,
        imagem: '/produtos/conjunto-esportivo.png',
    },
    {
        quantidade: 1,
        descricao: 'MAQUINA DE SOLDA ELÉTRICA YAXUN',
        valor: 120.00,
        imagem: '/produtos/maquina-solda.png',
    },
    {
        quantidade: 3,
        descricao: 'IMPRESSORA MÓVEL TÉRMICA ANDROID VOQX',
        valor: 250.00,
        imagem: '/produtos/impressora.png',
    },
    {
        quantidade: 20,
        descricao: 'JAQUETA',
        valor: 60.00,
        imagem: '/produtos/jaqueta.png',
    },
    {
        quantidade: 2,
        descricao: 'CONTADOR DE DINHEIRO QUANTA',
        valor: 240.00,
        imagem: '/produtos/contador.png',
    },
    {
        quantidade: 2,
        descricao: 'SWITCH TP-LINK TL-SG1024D',
        valor: 200.00,
        imagem: '/produtos/switch-sg1024.png',
    },
    {
        quantidade: 1,
        descricao: 'SWITCH TP-LINK TL-SG108',
        valor: 80.00,
        imagem: '/produtos/switch-sg108.png',
    },
    {
        quantidade: 1,
        descricao: 'CAIXA DE SOM JBL GO 3',
        valor: 100.00,
        imagem: '/produtos/go3jbl.png',
    },
    {
        quantidade: 6,
        descricao: 'SSD HIKVISION C100 120GB',
        valor: 35.00,
        imagem: '/produtos/hdssdc100.png',
    },
    {
        quantidade: 3,
        descricao: 'HD EXTERNO SEAGATE EXPANSION 1TB',
        valor: 150.00,
        imagem: '/produtos/hdexterno.png',
    },
    {
        quantidade: 1,
        descricao: 'SWITCH TP-LINK TL-SG1016D',
        valor: 140.00,
        imagem: '/produtos/switch-sg1016d.png',
    },
    {
        quantidade: 26,
        descricao: 'PLACA MÃE GOLINE GL-HSS-MA',
        valor: 60.00,
        imagem: '/produtos/placa-mae.png',
    },
    {
        quantidade: 1,
        descricao: 'SCOOTER ELÉTRICO HOVERBOARD 6,5',
        valor: 250.00,
        imagem: '/produtos/scooter.png',
    },
    {
        quantidade: 375,
        descricao: 'SSD BEST MEMORY 240GB',
        valor: 60.00,
        imagem: '/produtos/hdssd.png',
    },
    {
        quantidade: 1,
        descricao: 'MALA DE VIAGEM GRANDE',
        valor: 50.00,
        imagem: '/produtos/mala.png',
    },
    {
        quantidade: 44,
        descricao: 'PEÇAS VEICULARES',
        valor: 5.00,
        imagem: '/produtos/pecas.jpeg',
    },
    {
        quantidade: 15,
        descricao: 'PREENCHEDOR DE VOLUME RADIESSE 1.5 CC',
        valor: 300.00,
        imagem: '/produtos/preenchedor.jpg',
    },
    {
        quantidade: 56,
        descricao: 'LINE LIFT Y2SKIN',
        valor: 100.00,
        imagem: '/produtos/linelift.jpg',
    },
];

export default produtos; 